import Header from "@/components/ui/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import ThemeProvider from "@/components/wrapper/ThemeWrapper";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
  variable: "--font-nunitosans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${nunitoSans.className} bg-lightGray dark:bg-darkBlue-200`}
        >
          <Header />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
